Merge changes from main

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -30,7 +30,18 @@ jobs:
       lowercase-github-repository_owner: ${{ steps.github-repository_owner.outputs.lowercase }}
       ytdlp-latest-release: ${{ steps.yt-dlp.outputs.latest-release }}
       ytdlp-releases: ${{ steps.yt-dlp.outputs.releases }}
+      missing-tags: ${{ steps.tagged.outputs.missing }}
+      missing-tags-image: ${{ steps.tagged.outputs.image }}
     steps:
+      - name: Pull tagged releases
+        id: tagged
+        run: |
+          image='ghcr.io/meeb/${{ env.IMAGE_NAME }}'
+          missing=''
+          set_sl_var() { local f='%s=%s\n' ; printf -- "${f}" "$@" ; } ;
+          set -eux
+          set_sl_var image "${image}" >> "${GITHUB_OUTPUT}"
+          set_sl_var missing "${missing}" >> "${GITHUB_OUTPUT}"
       - uses: actions/checkout@v4
       - name: Lowercase github username
         id: github-actor
@@ -103,6 +114,8 @@ jobs:
             pip install --system --strict --requirements requirements.txt
       - name: Set up Django environment
         run: |
+          mkdir -v -p ~/.config/TubeSync/config
+          sudo ln -v -s -f -T ~/.config/TubeSync/config /config
           cp -v -p tubesync/tubesync/local_settings.py.example tubesync/tubesync/local_settings.py
           cp -v -a -t "${Python3_ROOT_DIR}"/lib/python3.*/site-packages/background_task/ patches/background_task/*
           cp -v -a -t "${Python3_ROOT_DIR}"/lib/python3.*/site-packages/yt_dlp/ patches/yt_dlp/*
@@ -168,6 +181,21 @@ jobs:
           DOCKER_USERNAME: ${{ github.actor }}
           DOCKER_TOKEN: ${{ 'meeb' == github.repository_owner && secrets.REGISTRY_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
         run: echo "${DOCKER_TOKEN}" | docker login --password-stdin --username "${DOCKER_USERNAME}" "${DOCKER_REGISTRY}"
+      - name: Push missing release tags
+        if: ${{ false && 'meeb' == github.actor && github.actor == github.repository_owner && '' != needs.info.outputs.missing-tags }}
+        run: |
+          missing='${{ needs.info.outputs.missing-tags }}'
+          image='${{ needs.info.outputs.missing-tags-image }}'
+          printf -- '%s\n' "${missing}" | tr '|' '\n' | \
+            while read SPEC
+            do
+              printf -- '%s\n' "${SPEC}" | ( IFS='=' ; \
+                read tag source && \
+                docker pull "${source}" && \
+                docker tag "${source}" "${image}:${tag}" && \
+                docker push "${image}:${tag}" ;
+              )
+            done
       - name: Build image for `dive`
         id: build-dive-image
         uses: docker/build-push-action@v6
